image: docker:latest
services:
    - docker:dind
variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
stages:
  - test
test:
  stage: test
  image: haelty/rust-test-cross
  only:
    - master
  script:
    - docker --version
    - docker pull "haelty/rust-test-cross"
    - cross build --target armv7-unknown-linux-gnueabihf --release
