[package]
name = "light_control"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
rumqttc = { version = "0.20" }
serde = { version = "1.0", features = ["derive"] }
url = "2.3"
serde_json = "1.0"
